module.exports = CardCollectionView = Backbone.View.extend({
  // Linking to element on the page
  el: $('#card-collection'),

  initialize: function() {
    this.collection.on('reset', this.render, this);
    this.collection.on('add', this.addCard, this);
  },

  render: function() {
    // Clear in case
    $(this.el).empty();
    // Using addCard method to preserve context of 'this' in forEach
    this.collection.forEach(this.addCard, this);
  },

  addCard: function(card) {
    var cardView = new CardView({ model: card });
    // Appending the html generated by CardView's render function
    $(this.el).append(cardView.render().el);
    console.log(this.el);
  }
});
