var LoadingTemplate = require('views/templates/loading'),
    CardIndexTemplate = require('views/templates/card/index');

module.exports = CardCollectionView = Backbone.View.extend({
  // Linking to element on the page
  el: $('#main'),
  template: CardIndexTemplate,
  loadingTemplate: LoadingTemplate,

  initialize: function() {
    $(this.el).html(this.loadingTemplate({ item: 'card' }));
    this.collection.on('reset', this.render, this);
    this.collection.on('add', this.addCard, this);
  },

  render: function() {
    $(this.el).html(this.template());
    // Using addCard method to preserve context of 'this' in forEach
    this.collection.forEach(this.addCard, this);
    // TODO clean up technical debt
  },

  addCard: function(card) {
    var cardView = new CardView({ model: card });
    // Appending the html generated by CardView's render function
    $(this.el).append(cardView.render().el);
    console.log(this.el);
  }
});
